### ISSUE TITLE
Rename project to mapper_icij

### ISSUE THREAD

**Issue by jbutcher21** [Senzing/mapper-icij#16]
To correct the initials ... it should have been ICIJ not IJIC

ICIJ stands for International Consortium of Investigative Journalists

**Comment by docktermj** [comment]
@jbutcher21 Renamed.  If it meets with your approval, please close the issue.

**Comment by jbutcher21** [comment]
My mistake Michael, the standard is a dash not an underscore.  Can you please change to mapper-icij?

Jeff Butcher
Senzing, Chief Architect
***@***.******@***.***>

Follow Senzing on Twitter<https://twitter.com/senzing> | LinkedIn<https://www.linkedin.com/company/senzing-inc/> | Facebook<https://www.facebook.com/senzinginc/> | Blog<https://senzing.com/category/senzing-blog/>

If you are not an intended recipient of confidential and privileged information in this email, please delete it, notify the sender immediately, and do not use or disseminate such information.


From: Michael Dockter ***@***.***>
Date: Thursday, July 15, 2021 at 6:01 AM
To: Senzing/mapper_icij ***@***.***>
Cc: Jeff Butcher ***@***.***>, Mention ***@***.***>
Subject: Re: [Senzing/mapper_icij] Rename project to mapper_icij (#16)

@jbutcher21<https://github.com/jbutcher21> Renamed. If it meets with your approval, please close the issue.

**Comment by docktermj** [comment]
@jbutcher21 My apologies.  I simply copied it from the title of the issue.     It's fixed.   Thanks for catching that!

**Comment by jbutcher21** [comment]
I renamed the artifacts and documentation as well.   All done!
